// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfS3RlinVAqGdOnG8uIQlcUHaXU6htwG4',
    appId: '1:132647805775:web:63687b2541e75f71cbdb3a',
    messagingSenderId: '132647805775',
    projectId: 'mp9-alpha',
    authDomain: 'mp9-alpha.firebaseapp.com',
    storageBucket: 'mp9-alpha.firebasestorage.app',
    measurementId: 'G-EYC5SKYFSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkFv1b0xc0rv48MHx6ccqNKbmAsxNmt14',
    appId: '1:132647805775:android:13020711849a2ddccbdb3a',
    messagingSenderId: '132647805775',
    projectId: 'mp9-alpha',
    storageBucket: 'mp9-alpha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbYH7VXP84D0aXBShPI7e8XBF1JXCJS40',
    appId: '1:132647805775:ios:8b06b88ba275d2b4cbdb3a',
    messagingSenderId: '132647805775',
    projectId: 'mp9-alpha',
    storageBucket: 'mp9-alpha.firebasestorage.app',
    iosClientId: '132647805775-hlidhfiumjqi6gq4be7034cckij865sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfS3RlinVAqGdOnG8uIQlcUHaXU6htwG4',
    appId: '1:132647805775:web:0e39865dd85de02bcbdb3a',
    messagingSenderId: '132647805775',
    projectId: 'mp9-alpha',
    authDomain: 'mp9-alpha.firebaseapp.com',
    storageBucket: 'mp9-alpha.firebasestorage.app',
    measurementId: 'G-W7DW0B0RCM',
  );
}
